-- Auto-incrément lisible pour les runtimes, à côté de l'UUID technique.
-- Affiché dans l'UI comme "#42" pour référencer un runtime de façon humaine.
ALTER TABLE project_runtimes
    ADD COLUMN IF NOT EXISTS seq BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE;

ALTER TABLE project_group_runtimes
    ADD COLUMN IF NOT EXISTS seq BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE;
