from __future__ import annotations

import json
import os
import re
import secrets
from collections.abc import AsyncIterator
from datetime import datetime
from typing import Any

import aiodocker
import structlog

from agflow.mom.adapters.generic import GenericAdapter
from agflow.mom.adapters.mistral import MistralAdapter
from agflow.schemas.containers import ContainerInfo

_log = structlog.get_logger(__name__)

_ADAPTER_REGISTRY: dict[str, type[GenericAdapter]] = {
    "mistral": MistralAdapter,
    "generic": GenericAdapter,
}


def get_adapter(dockerfile_id: str) -> GenericAdapter:
    """Return the adapter instance for a given dockerfile type.

    Falls back to GenericAdapter if the dockerfile_id is unknown.
    """
    adapter_cls = _ADAPTER_REGISTRY.get(dockerfile_id, GenericAdapter)
    return adapter_cls()

# How many agflow-managed containers can run at once. Hard limit to avoid
# accidental resource exhaustion on the test LXC.
MAX_RUNNING_CONTAINERS = 10

_AGFLOW_MANAGED_LABEL = "agflow.managed"
_AGFLOW_DOCKERFILE_LABEL = "agflow.dockerfile_id"
_AGFLOW_INSTANCE_LABEL = "agflow.instance_id"

_TEMPLATE_RE = re.compile(r"(?<!\$)\{(\w+)\}")
# Matches ${VAR} and ${VAR:-default} — standard shell templating that the
# user would expect to be expanded before docker sees it. Because we call
# docker via HTTP API (no shell in between), we do the expansion ourselves
# against os.environ.
_SHELL_VAR_RE = re.compile(r"\$\{(\w+)(?::-([^}]*))?\}")


def _generate_tmp_files(
    dockerfile_id: str,
    container_name: str,
    config: dict[str, Any],
    task_payload: dict[str, Any] | None = None,
) -> str:
    """Generate .env + run.sh (+ task.json if task_payload) in {AGFLOW_DATA_DIR}/{dockerfile_id}/.tmp/.

    Returns the absolute path of the generated run.sh. When task_payload is
    provided, run.sh is generated in "task mode": ``docker run -i … < task.json``
    so the container's entrypoint reads the task on stdin.
    """
    import json as _json

    data_dir = os.environ.get("AGFLOW_DATA_DIR", "/app/data")
    tmp_dir = os.path.join(data_dir, dockerfile_id, ".tmp")
    os.makedirs(tmp_dir, exist_ok=True)

    # .env — all resolved env vars
    env_list = config.get("Env", [])
    env_content = "\n".join(env_list) + "\n"
    with open(os.path.join(tmp_dir, ".env"), "w", encoding="utf-8") as f:
        f.write(env_content)

    # task.json — payload piped to the container's entrypoint via stdin
    if task_payload is not None:
        task_path = os.path.join(tmp_dir, "task.json")
        with open(task_path, "w", encoding="utf-8") as f:
            _json.dump(task_payload, f, ensure_ascii=False)
            f.write("\n")

    # run.sh
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by agflow — do not edit",
        'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
        'set -a; source "$SCRIPT_DIR/.env"; set +a',
        "",
    ]
    cmd_parts = ["docker run --rm"]
    if task_payload is not None:
        cmd_parts.append("-i")
    cmd_parts.append(f"--name {container_name}")
    host_config = config.get("HostConfig", {})
    if host_config.get("NetworkMode"):
        cmd_parts.append(f"--network {host_config['NetworkMode']}")
    if host_config.get("Init"):
        cmd_parts.append("--init")
    for label_key, label_value in (config.get("Labels") or {}).items():
        cmd_parts.append(f'--label "{label_key}={label_value}"')
    for bind in host_config.get("Binds", []):
        cmd_parts.append(f'-v "{bind}"')
    if host_config.get("Memory"):
        mem_mb = host_config["Memory"] // (1024 * 1024)
        cmd_parts.append(f"--memory {mem_mb}m")
    if host_config.get("NanoCpus"):
        cpus = host_config["NanoCpus"] / 1_000_000_000
        cmd_parts.append(f"--cpus {cpus}")
    if config.get("WorkingDir"):
        cmd_parts.append(f"-w {config['WorkingDir']}")
    for env_line in env_list:
        key = env_line.split("=", 1)[0]
        cmd_parts.append(f'-e "{key}=${{{key}}}"')
    cmd_parts.append(config.get("Image", ""))
    docker_cmd = " \\\n  ".join(cmd_parts)
    if task_payload is not None:
        docker_cmd += ' < "$SCRIPT_DIR/task.json"'
    lines.append(docker_cmd)
    lines.append("")

    run_path = os.path.join(tmp_dir, "run.sh")
    with open(run_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    os.chmod(run_path, 0o755)

    _log.info("container.generate_tmp", dockerfile_id=dockerfile_id, tmp_dir=tmp_dir)
    return run_path


async def _load_platform_secrets() -> dict[str, str]:
    """Load all global platform secrets as a dict for env var injection."""
    from agflow.config import get_settings
    from agflow.db.pool import fetch_all

    master = get_settings().secrets_master_key
    rows = await fetch_all(
        """
        SELECT var_name, pgp_sym_decrypt(value_encrypted, $1) AS value
        FROM secrets
        WHERE scope = 'global'
        """,
        master,
    )
    return {r["var_name"]: r["value"] for r in rows}


class ContainerRunnerError(Exception):
    """Base class for predictable errors raised by the runner."""


class ImageNotBuiltError(ContainerRunnerError):
    pass


class TooManyContainersError(ContainerRunnerError):
    pass


class ContainerNotFoundError(ContainerRunnerError):
    pass


class InvalidParamsError(ContainerRunnerError):
    pass


# ─────────────────────────────────────────────────────────────
# Template resolver — mirrors the frontend semantics:
#   {KEY}      → lookup in vars, recursive until stable
#   ${VAR}     → left untouched (shell-level templating)
# ─────────────────────────────────────────────────────────────
def resolve_templates(
    s: str, vars: dict[str, str], max_iter: int = 16
) -> str:
    if not s:
        return s
    current = s
    for _ in range(max_iter):
        next_val = _TEMPLATE_RE.sub(
            lambda m: vars.get(m.group(1), m.group(0)), current
        )
        if next_val == current:
            return next_val
        current = next_val
    return current


def expand_shell_vars(s: str, extra_env: dict[str, str] | None = None) -> str:
    """Expand ${VAR} and ${VAR:-default} against os.environ + extra_env.

    Called AFTER agflow's own {KEY} resolution. Missing env vars fall back
    to the ``:-default`` clause if present, otherwise to an empty string.

    Self-references (e.g. a Param ``WORKSPACE_PATH = "${WORKSPACE_PATH:-./x}"``
    that ends up looking itself up via merged_env) are detected: if the value
    obtained for ``VAR`` still mentions ``${VAR}``, we treat the lookup as a
    miss and fall back to the inline default. Without this guard, the
    self-referencing string would leak through to the consumer (Docker, the
    .env file, etc.) and produce nonsense like ``invalid mode`` errors when
    used inside bind mounts.
    """
    if not s:
        return s
    merged = {**os.environ, **(extra_env or {})}

    def replacer(m: "re.Match[str]") -> str:
        var_name = m.group(1)
        default = m.group(2) or ""
        value = merged.get(var_name)
        if value is None:
            return default
        if f"${{{var_name}}}" in value or f"${{{var_name}:-" in value:
            return default
        return value

    return _SHELL_VAR_RE.sub(replacer, s)


def full_resolve(
    s: str, vars: dict[str, str], extra_env: dict[str, str] | None = None
) -> str:
    """agflow {KEY} templating followed by shell ${VAR} expansion.

    Shell ${VAR} expansion looks up in params (vars) AND secrets (extra_env),
    so ${SOME_PARAM} resolves to its Params value and ${SOME_SECRET} resolves
    to its vault value. Secrets override params on name collision.
    """
    merged_env = {**vars, **(extra_env or {})}
    return expand_shell_vars(resolve_templates(s, vars), merged_env)


def _data_host_dir() -> str:
    return os.environ.get("AGFLOW_DATA_HOST_DIR", "/app/data").rstrip("/")


def _data_container_dir() -> str:
    return os.environ.get("AGFLOW_DATA_DIR", "/app/data").rstrip("/")


def resolve_mount_source(
    raw_source: str,
    dockerfile_id: str,
    vars: dict[str, str],
    extra_env: dict[str, str] | None = None,
) -> tuple[str, str | None, bool]:
    """Resolve a user-supplied mount source to the path Docker should use.

    Returns a triplet:
      * host_path          — the absolute host path to pass to Docker.
      * container_path     — same file as seen from the backend container,
                             used for existence checks. ``None`` if the
                             resolved source was already absolute (we don't
                             reach into arbitrary host paths from here).
      * auto_prefixed      — True if we auto-prefixed the source under
                             ``{HOST_DIR}/{slug}/``; False if it was kept
                             as-is because it was already absolute.

    Rules:
      1. Run the full templating (agflow {KEY} + shell ${VAR}) first.
      2. If the resolved path starts with ``/`` → keep as-is (user wants an
         explicit host path). No auto-prefix, no existence check.
      3. Otherwise → strip any leading ``./`` and prepend
         ``{AGFLOW_DATA_HOST_DIR}/{slug}/``. The same path under
         ``{AGFLOW_DATA_DIR}/{slug}/`` is returned for existence checks.
    """
    resolved = full_resolve(raw_source, vars, extra_env).strip()
    if resolved.startswith("/"):
        return resolved, None, False

    if resolved.startswith("./"):
        resolved = resolved[2:]
    resolved = resolved.lstrip("/")

    host_path = f"{_data_host_dir()}/{dockerfile_id}/{resolved}"
    container_path = f"{_data_container_dir()}/{dockerfile_id}/{resolved}"
    return host_path, container_path, True


def check_mount_source(container_path: str | None) -> bool | None:
    """Existence check for an auto-prefixed mount source.

    Returns ``True`` / ``False`` if the path can be checked via the backend
    container's view of the data dir, or ``None`` for absolute paths that
    were passed through (we can't reach host-only paths from here).
    """
    if container_path is None:
        return None
    return os.path.isfile(container_path) or os.path.isdir(container_path)


def _looks_like_directory(path: str) -> bool:
    """Heuristic: a path segment with a '.' in its name is treated as a file
    (e.g. ``auth.json``, ``.env``, ``config.yml``). Everything else is
    treated as a directory and will be auto-created at launch time.
    """
    tail = path.rsplit("/", 1)[-1]
    return "." not in tail


def _ensure_mount_paths_from_config(
    dockerfile_id: str,
    params_json_content: str,
    instance_id: str,
    content_hash: str,
) -> None:
    """Helper that reparses Dockerfile.json and calls ensure_mount_paths."""
    try:
        root = json.loads(params_json_content) if params_json_content else {}
    except json.JSONDecodeError:
        return
    if not isinstance(root, dict):
        return
    docker_cfg = root.get("docker") or {}
    params = root.get("Params") or {}
    mounts = docker_cfg.get("Mounts") if isinstance(docker_cfg, dict) else None
    if not isinstance(mounts, list):
        return
    user_vars = {
        k: str(v) for k, v in params.items() if isinstance(v, (str, int, float))
    } if isinstance(params, dict) else {}
    system_vars = {
        "slug": dockerfile_id,
        "hash": content_hash,
        "id": instance_id,
    }
    try:
        ensure_mount_paths(dockerfile_id, mounts, {**user_vars, **system_vars})
    except OSError as exc:
        _log.warning(
            "container.ensure_mount_paths.failed",
            dockerfile_id=dockerfile_id,
            error=str(exc),
        )


def ensure_mount_paths(
    dockerfile_id: str,
    mounts: list[dict[str, Any]],
    vars: dict[str, str],
) -> list[str]:
    """For each auto-prefixed mount, pre-create the parent directory and,
    for directory-like sources, the destination itself.

    This lets the user use `workspace` as a mount source without having to
    `mkdir -p` first — the directory appears on the host at launch time.
    For file sources (e.g. `auth.json`), only the parent is created, so the
    user still has to place the actual file.

    Returns a list of warnings for mounts that could not be auto-prepared
    (e.g. file sources that still don't exist after ensuring the parent).
    """
    warnings: list[str] = []
    for m in mounts:
        if not isinstance(m, dict):
            continue
        raw_source = str(m.get("source", "")).strip()
        if not raw_source:
            continue
        _host, container_path, auto_prefixed = resolve_mount_source(
            raw_source, dockerfile_id, vars
        )
        if not auto_prefixed or container_path is None:
            continue
        try:
            if _looks_like_directory(container_path):
                os.makedirs(container_path, exist_ok=True)
            else:
                os.makedirs(os.path.dirname(container_path), exist_ok=True)
                if not os.path.exists(container_path):
                    warnings.append(
                        f"Mount source file is missing: {container_path} "
                        f"(parent directory was prepared — place the file there)"
                    )
        except OSError as exc:
            warnings.append(
                f"Could not create mount path {container_path}: {exc}"
            )
    return warnings


def _resolve_list(
    items: list[dict[str, Any]] | None,
    vars: dict[str, str],
    extra_env: dict[str, str] | None = None,
) -> list[dict[str, Any]]:
    if not items:
        return []
    out: list[dict[str, Any]] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        resolved: dict[str, Any] = {}
        for k, v in item.items():
            if isinstance(v, str):
                resolved[k] = full_resolve(v, vars, extra_env)
            else:
                resolved[k] = v
        out.append(resolved)
    return out


def _resolve_dict(
    d: dict[str, Any] | None,
    vars: dict[str, str],
    extra_env: dict[str, str] | None = None,
) -> dict[str, str]:
    if not d:
        return {}
    out: dict[str, str] = {}
    for k, v in d.items():
        if isinstance(v, str):
            out[k] = full_resolve(v, vars, extra_env)
        else:
            out[k] = str(v)
    return out


# ─────────────────────────────────────────────────────────────
# Resource parsers
# ─────────────────────────────────────────────────────────────
_MEMORY_UNITS = {"b": 1, "k": 1024, "m": 1024**2, "g": 1024**3}


def parse_memory_bytes(raw: str) -> int:
    """Parse docker-style memory like '512m', '2g', '1024k' to bytes.
    Returns 0 if the string is empty or 0 — means 'no limit'.
    """
    s = (raw or "").strip().lower()
    if not s:
        return 0
    m = re.match(r"^(\d+(?:\.\d+)?)\s*([bkmg]?)$", s)
    if not m:
        raise InvalidParamsError(f"Invalid memory value: '{raw}'")
    value = float(m.group(1))
    if value <= 0:
        return 0
    unit = m.group(2) or "b"
    return int(value * _MEMORY_UNITS[unit])


def parse_nano_cpus(raw: str) -> int:
    """Parse docker-style cpu count like '1.5' to nano CPUs (1 CPU = 1e9)."""
    s = (raw or "").strip()
    if not s:
        return 0
    try:
        value = float(s)
    except ValueError as exc:
        raise InvalidParamsError(f"Invalid cpu value: '{raw}'") from exc
    if value <= 0:
        return 0
    return int(value * 1_000_000_000)


# ─────────────────────────────────────────────────────────────
# Build docker run config from Dockerfile.json + current hash
# ─────────────────────────────────────────────────────────────
def build_run_config(
    *,
    dockerfile_id: str,
    params_json_content: str,
    content_hash: str,
    instance_id: str,
    extra_env: dict[str, str] | None = None,
) -> tuple[str, dict[str, Any]]:
    """Parse Dockerfile.json and produce (container_name, aiodocker config).

    The returned config follows the Docker Engine API payload shape expected
    by `aiodocker.Docker().containers.create(config=..., name=...)`.
    """
    try:
        root = json.loads(params_json_content) if params_json_content else {}
    except json.JSONDecodeError as exc:
        raise InvalidParamsError(
            f"Dockerfile.json is not valid JSON: {exc.msg}"
        ) from exc

    if not isinstance(root, dict):
        raise InvalidParamsError("Dockerfile.json root must be an object")

    docker_cfg = root.get("docker") or {}
    params = root.get("Params") or {}
    if not isinstance(docker_cfg, dict) or not isinstance(params, dict):
        raise InvalidParamsError(
            "Dockerfile.json must have 'docker' and 'Params' objects"
        )

    # Apply exclusions from Dockerfile.json Excluded section
    excluded = root.get("Excluded") or {}
    if isinstance(excluded, dict):
        excluded_envs = set(excluded.get("environments", []))
        excluded_mounts = set(excluded.get("mounts", []))
        excluded_params = set(excluded.get("params", []))
        envs = docker_cfg.get("Environments")
        if isinstance(envs, dict):
            docker_cfg["Environments"] = {k: v for k, v in envs.items() if k not in excluded_envs}
        mounts = docker_cfg.get("Mounts")
        if isinstance(mounts, list):
            docker_cfg["Mounts"] = [m for m in mounts if m.get("target") not in excluded_mounts]
        params = {k: v for k, v in params.items() if k not in excluded_params}

    # Resolution variables — user Params first, then system vars (system
    # values always win over user-defined ones).
    user_vars: dict[str, str] = {
        k: str(v) for k, v in params.items() if isinstance(v, (str, int, float))
    }
    system_vars = {
        "slug": dockerfile_id,
        "hash": content_hash,
        "id": instance_id,
    }
    vars_map = {**user_vars, **system_vars}

    container = docker_cfg.get("Container") or {}
    network = docker_cfg.get("Network") or {}
    runtime = docker_cfg.get("Runtime") or {}
    resources = docker_cfg.get("Resources") or {}
    environments = docker_cfg.get("Environments") or {}
    mounts = docker_cfg.get("Mounts") or []

    name = full_resolve(str(container.get("Name", "")), vars_map, extra_env).strip()
    if not name:
        raise InvalidParamsError("Container.Name template resolved to empty")

    # Environment vars: docker expects list of "KEY=VALUE".
    env_dict = _resolve_dict(
        environments if isinstance(environments, dict) else {}, vars_map, extra_env
    )
    env_list = [f"{k}={v}" for k, v in env_dict.items()]

    # Mounts → Binds ("source:target[:ro]"). Source goes through the
    # auto-prefix + shell-expand pipeline; target is a literal container
    # path after {KEY} + ${VAR} resolution.
    raw_mounts = mounts if isinstance(mounts, list) else []
    binds: list[str] = []
    for m in raw_mounts:
        if not isinstance(m, dict):
            continue
        raw_source = str(m.get("source", "")).strip()
        target = full_resolve(str(m.get("target", "")).strip(), vars_map, extra_env)
        if not raw_source or not target:
            continue
        host_source, _container_path, _auto = resolve_mount_source(
            raw_source, dockerfile_id, vars_map, extra_env
        )
        ro_flag = ":ro" if bool(m.get("readonly")) else ""
        binds.append(f"{host_source}:{target}{ro_flag}")

    network_mode = full_resolve(
        str(network.get("Mode", "bridge")), vars_map, extra_env
    ) or "bridge"

    memory_bytes = parse_memory_bytes(str(resources.get("Memory", "")))
    nano_cpus = parse_nano_cpus(str(resources.get("Cpus", "")))

    stop_signal = str(runtime.get("StopSignal", "SIGTERM")) or "SIGTERM"
    stop_timeout_raw = runtime.get("StopTimeout", 30)
    try:
        stop_timeout = int(stop_timeout_raw)
    except (TypeError, ValueError) as exc:
        raise InvalidParamsError(
            f"Runtime.StopTimeout must be an integer, got {stop_timeout_raw!r}"
        ) from exc
    working_dir = full_resolve(str(runtime.get("WorkingDir", "")), vars_map, extra_env) or None
    init_enabled = bool(runtime.get("Init", True))
    # Tty + OpenStdin: opt-in via Runtime block. When True, the container is
    # allocated a TTY and keeps stdin open, mimicking `docker run -ti`. The
    # process inside stays alive while stdin remains open, which lets the
    # operator `docker exec -ti <id>` for exploration even when the entrypoint
    # would normally exit immediately (e.g. it expects a task on stdin).
    tty_enabled = bool(runtime.get("Tty", False))
    open_stdin = bool(runtime.get("OpenStdin", False))

    image_template = str(
        container.get("Image", f"agflow-{dockerfile_id}:{{hash}}")
    )
    image = full_resolve(image_template, vars_map, extra_env)

    host_config: dict[str, Any] = {
        "NetworkMode": network_mode,
        "Init": init_enabled,
        "Binds": binds,
        "AutoRemove": False,
    }
    if memory_bytes > 0:
        host_config["Memory"] = memory_bytes
    if nano_cpus > 0:
        host_config["NanoCpus"] = nano_cpus
    if stop_timeout >= 0:
        host_config["StopTimeout"] = stop_timeout

    labels = {
        _AGFLOW_MANAGED_LABEL: "true",
        _AGFLOW_DOCKERFILE_LABEL: dockerfile_id,
        _AGFLOW_INSTANCE_LABEL: instance_id,
    }

    config: dict[str, Any] = {
        "Image": image,
        "Env": env_list,
        "Labels": labels,
        "StopSignal": stop_signal,
        "Tty": tty_enabled,
        "OpenStdin": open_stdin,
        "StdinOnce": False if open_stdin else True,
        "HostConfig": host_config,
    }
    if working_dir:
        config["WorkingDir"] = working_dir

    return name, config


# ─────────────────────────────────────────────────────────────
# Container lifecycle via aiodocker
# ─────────────────────────────────────────────────────────────
def _parse_docker_ts(raw: str) -> datetime:
    # Docker returns ISO-8601 with nanosecond precision; trim to microseconds
    # so datetime.fromisoformat is happy. "2024-01-02T03:04:05.123456789Z"
    # → "2024-01-02T03:04:05.123456+00:00".
    s = raw.rstrip("Z")
    if "." in s:
        head, frac = s.split(".", 1)
        frac = frac[:6]
        s = f"{head}.{frac}"
    return datetime.fromisoformat(s + "+00:00")


def _info_from_container(raw: dict[str, Any]) -> ContainerInfo:
    labels = raw.get("Labels") or {}
    names = raw.get("Names") or []
    name = (names[0] if names else raw.get("Name", "")).lstrip("/")
    created = raw.get("Created")
    if isinstance(created, (int, float)):
        created_at = datetime.fromtimestamp(created)
    elif isinstance(created, str):
        created_at = _parse_docker_ts(created)
    else:
        created_at = datetime.now()
    return ContainerInfo(
        id=raw.get("Id", raw.get("ID", "")),
        name=name,
        dockerfile_id=labels.get(_AGFLOW_DOCKERFILE_LABEL, ""),
        image=raw.get("Image", ""),
        status=raw.get("State", "created"),
        created_at=created_at,
        instance_id=labels.get(_AGFLOW_INSTANCE_LABEL, ""),
    )


async def list_running() -> list[ContainerInfo]:
    """List all agflow-managed containers (running or stopped)."""
    docker = aiodocker.Docker()
    try:
        containers = await docker.containers.list(
            all=True,
            filters={"label": [f"{_AGFLOW_MANAGED_LABEL}=true"]},
        )
        result: list[ContainerInfo] = []
        for c in containers:
            # Show() returns the full inspect payload which has Config.Labels.
            inspect = await c.show()
            cfg = inspect.get("Config") or {}
            state = inspect.get("State") or {}
            labels = cfg.get("Labels") or {}
            created_at = _parse_docker_ts(inspect.get("Created", ""))
            result.append(
                ContainerInfo(
                    id=inspect.get("Id", ""),
                    name=(inspect.get("Name") or "").lstrip("/"),
                    dockerfile_id=labels.get(_AGFLOW_DOCKERFILE_LABEL, ""),
                    image=cfg.get("Image", ""),
                    status=state.get("Status", "created"),
                    created_at=created_at,
                    instance_id=labels.get(_AGFLOW_INSTANCE_LABEL, ""),
                )
            )
        return result
    finally:
        await docker.close()


async def start(
    dockerfile_id: str,
    *,
    params_json_content: str,
    content_hash: str,
    user_secrets: dict[str, str] | None = None,
) -> ContainerInfo:
    """Create and start a container for a given dockerfile.

    Raises:
        ImageNotBuiltError: the target image does not exist yet.
        TooManyContainersError: the hard limit of running containers is reached.
        InvalidParamsError: Dockerfile.json cannot be translated to a config.
    """
    # Enforce concurrency limit before touching docker.
    existing = await list_running()
    alive = [c for c in existing if c.status in ("running", "created", "restarting")]
    if len(alive) >= MAX_RUNNING_CONTAINERS:
        raise TooManyContainersError(
            f"Maximum of {MAX_RUNNING_CONTAINERS} running containers reached. "
            f"Stop one before launching another."
        )

    instance_id = secrets.token_hex(3)
    platform_secrets = await _load_platform_secrets()
    # Merge: platform secrets + user secrets (user wins)
    all_secrets = {**platform_secrets, **(user_secrets or {})}
    name, config = build_run_config(
        dockerfile_id=dockerfile_id,
        params_json_content=params_json_content,
        content_hash=content_hash,
        instance_id=instance_id,
        extra_env=all_secrets,
    )

    # Pre-create auto-prefixed mount directories so the default workspace/
    # output/... mounts "just work" without the user having to mkdir first.
    _ensure_mount_paths_from_config(
        dockerfile_id, params_json_content, instance_id, content_hash
    )

    # Generate .tmp/ files (run.sh + .env) before launching
    _generate_tmp_files(dockerfile_id, name, config)

    docker = aiodocker.Docker()
    try:
        try:
            await docker.images.inspect(config["Image"])
        except aiodocker.exceptions.DockerError as exc:
            if exc.status == 404:
                raise ImageNotBuiltError(
                    f"Image '{config['Image']}' not found — build the dockerfile first."
                ) from exc
            raise

        container = await docker.containers.create(config=config, name=name)
        await container.start()
        inspect = await container.show()

        cfg = inspect.get("Config") or {}
        state = inspect.get("State") or {}
        labels = cfg.get("Labels") or {}
        info = ContainerInfo(
            id=inspect.get("Id", ""),
            name=(inspect.get("Name") or "").lstrip("/"),
            dockerfile_id=labels.get(_AGFLOW_DOCKERFILE_LABEL, dockerfile_id),
            image=cfg.get("Image", config["Image"]),
            status=state.get("Status", "running"),
            created_at=_parse_docker_ts(inspect.get("Created", "")),
            instance_id=labels.get(_AGFLOW_INSTANCE_LABEL, instance_id),
        )
        _log.info(
            "container.start",
            dockerfile_id=dockerfile_id,
            container_id=info.id,
            name=info.name,
        )
        return info
    finally:
        await docker.close()


async def run_task(
    dockerfile_id: str,
    *,
    params_json_content: str,
    content_hash: str,
    task_payload: dict[str, Any],
    timeout_seconds: int = 600,
    user_secrets: dict[str, str] | None = None,
    on_container_started: Any | None = None,
    cleanup: bool = False,
    session_id: str | None = None,
) -> AsyncIterator[dict[str, Any]]:
    """One-shot: regenerate .tmp/{.env, run.sh, task.json} then exec run.sh.

    The launch uses the exact ``run.sh`` the user can run by hand for
    diagnosis — same .env, same docker run command, same stdin pipe. We
    subprocess ``bash run.sh`` and stream its stdout as newline-delimited
    JSON events.

    Yields parsed event dicts as they arrive, plus a final
    ``{"type": "done", "status": "success" | "failure", "exit_code": N}``.

    When ``cleanup=True`` (Module 1 chat de test), ``.tmp/`` is removed and
    any surviving container is force-deleted after the task. Module 4
    launches keep the generated files as the production artefact.
    """
    import asyncio as _asyncio
    import json as _json
    import secrets as _secrets
    import shutil as _shutil

    import aiodocker as _aiodocker

    # Concurrency guard — shares the same limit as interactive containers.
    existing = await list_running()
    alive = [
        c for c in existing if c.status in ("running", "created", "restarting")
    ]
    if len(alive) >= MAX_RUNNING_CONTAINERS:
        raise TooManyContainersError(
            f"Maximum of {MAX_RUNNING_CONTAINERS} running containers reached."
        )

    session_id = session_id or _secrets.token_hex(6)
    instance_id = secrets.token_hex(3)
    platform_secrets = await _load_platform_secrets()
    all_secrets = {**platform_secrets, **(user_secrets or {})}
    name, config = build_run_config(
        dockerfile_id=dockerfile_id,
        params_json_content=params_json_content,
        content_hash=content_hash,
        instance_id=instance_id,
        extra_env=all_secrets,
    )
    _ensure_mount_paths_from_config(
        dockerfile_id, params_json_content, instance_id, content_hash
    )

    # Pre-flight: image must exist, otherwise fail early with a typed error
    # instead of letting docker CLI spew to stderr.
    _aio = _aiodocker.Docker()
    try:
        try:
            await _aio.images.inspect(config["Image"])
        except _aiodocker.exceptions.DockerError as exc:
            if exc.status == 404:
                raise ImageNotBuiltError(
                    f"Image '{config['Image']}' not found — build the dockerfile first."
                ) from exc
            raise
    finally:
        await _aio.close()

    from agflow.db.pool import get_pool
    from agflow.mom.envelope import Direction, Kind
    from agflow.mom.publisher import MomPublisher

    _mom_pool = await get_pool()
    _mom_publisher = MomPublisher(
        pool=_mom_pool,
        groups_config={
            Direction.IN: ["dispatcher"],
            Direction.OUT: ["ws_push", "router"],
        },
    )
    _in_msg_id = await _mom_publisher.publish(
        session_id=session_id,
        instance_id=instance_id,
        direction=Direction.IN,
        source="system",
        kind=Kind.INSTRUCTION,
        payload=task_payload,
    )
    _adapter = get_adapter(dockerfile_id)

    # Regenerate .tmp/{.env, run.sh, task.json} — run.sh is the source of
    # truth for the launch.
    run_sh = _generate_tmp_files(
        dockerfile_id=dockerfile_id,
        container_name=name,
        config=config,
        task_payload=task_payload,
    )
    tmp_dir = os.path.dirname(run_sh)

    proc: _asyncio.subprocess.Process | None = None
    try:
        proc = await _asyncio.create_subprocess_exec(
            "bash",
            run_sh,
            stdout=_asyncio.subprocess.PIPE,
            stderr=_asyncio.subprocess.STDOUT,
        )

        if on_container_started is not None:
            await on_container_started("", name)

        assert proc.stdout is not None

        deadline = _asyncio.get_event_loop().time() + max(1, timeout_seconds)
        timed_out = False
        try:
            while True:
                remaining = deadline - _asyncio.get_event_loop().time()
                if remaining <= 0:
                    timed_out = True
                    break
                try:
                    line = await _asyncio.wait_for(
                        proc.stdout.readline(), timeout=remaining
                    )
                except TimeoutError:
                    timed_out = True
                    break
                if not line:
                    break
                text = line.decode("utf-8", errors="replace").rstrip("\r\n")
                if not text:
                    continue

                try:
                    _parsed = _adapter.parse_stdout_line(text)
                    if _parsed is not None:
                        _kind, _payload, _route = _parsed
                        await _mom_publisher.publish(
                            session_id=session_id,
                            instance_id=instance_id,
                            direction=Direction.OUT,
                            source=f"agent:{instance_id}",
                            kind=_kind,
                            payload=_payload,
                            route=_route,
                            parent_msg_id=_in_msg_id,
                        )
                except Exception as _exc:
                    _log.warning("mom.publish_out_failed", error=str(_exc), text=text[:100])

                try:
                    yield _json.loads(text)
                except _json.JSONDecodeError:
                    yield {"type": "raw", "data": text}
        except _asyncio.CancelledError:
            proc.kill()
            await proc.wait()
            raise

        if timed_out:
            yield {"type": "error", "message": "Timeout"}
            proc.kill()
        await proc.wait()

        exit_code = proc.returncode or 0

        try:
            if timed_out:
                await _mom_publisher.publish(
                    session_id=session_id,
                    instance_id=instance_id,
                    direction=Direction.OUT,
                    source="system",
                    kind=Kind.ERROR,
                    payload={"message": "timeout", "timeout_seconds": timeout_seconds},
                    parent_msg_id=_in_msg_id,
                )
            elif exit_code != 0:
                await _mom_publisher.publish(
                    session_id=session_id,
                    instance_id=instance_id,
                    direction=Direction.OUT,
                    source="system",
                    kind=Kind.ERROR,
                    payload={
                        "message": f"container exited with code {exit_code}",
                        "exit_code": exit_code,
                    },
                    parent_msg_id=_in_msg_id,
                )
        except Exception as _exc:
            _log.warning("mom.publish_result_failed", error=str(_exc))

        yield {
            "type": "done",
            "status": "success" if exit_code == 0 else "failure",
            "exit_code": exit_code,
        }
    finally:
        # Best-effort: if the container is still around, force-remove it.
        if cleanup:
            try:
                _aio_cleanup = _aiodocker.Docker()
                try:
                    try:
                        container = await _aio_cleanup.containers.get(name)
                        await container.delete(force=True)
                    except _aiodocker.exceptions.DockerError:
                        pass
                finally:
                    await _aio_cleanup.close()
            except Exception:
                pass
            _shutil.rmtree(tmp_dir, ignore_errors=True)


async def stop(container_id: str) -> None:
    """Stop and remove a container by its Docker id."""
    docker = aiodocker.Docker()
    try:
        try:
            container = docker.containers.container(container_id=container_id)
            # Confirm it is agflow-managed before touching it.
            inspect = await container.show()
        except aiodocker.exceptions.DockerError as exc:
            if exc.status == 404:
                raise ContainerNotFoundError(
                    f"Container '{container_id}' not found"
                ) from exc
            raise

        labels = (inspect.get("Config") or {}).get("Labels") or {}
        if labels.get(_AGFLOW_MANAGED_LABEL) != "true":
            raise ContainerNotFoundError(
                f"Container '{container_id}' is not managed by agflow"
            )

        try:
            await container.stop(timeout=10)
        except aiodocker.exceptions.DockerError:
            # Already stopped or in a weird state — still try to remove.
            pass
        try:
            await container.delete(force=True)
        except aiodocker.exceptions.DockerError as exc:
            # 409 = "removal already in progress" (parallel click / polling
            # double-trigger). 404 = already gone. Both mean the container is
            # on its way out, treat as success.
            if exc.status not in (404, 409):
                raise
        _log.info("container.stop", container_id=container_id)
    finally:
        await docker.close()


async def publish_instruction_via_mom(
    *,
    session_id: str,
    instance_id: str,
    instruction: str,
) -> str:
    """Publish an IN instruction to the MOM bus.

    Returns the msg_id. This is a building block for the future
    MOM-driven task runner that will replace the subprocess-based flow.
    Full integration (dispatcher + aiodocker container wrapper) is
    tracked as a follow-up.
    """
    from agflow.db.pool import get_pool
    from agflow.mom.envelope import Direction, Kind
    from agflow.mom.publisher import MomPublisher

    pool = await get_pool()
    publisher = MomPublisher(
        pool=pool,
        groups_config={
            Direction.IN: ["dispatcher"],
            Direction.OUT: ["ws_push", "router"],
        },
    )
    msg_id = await publisher.publish(
        session_id=session_id,
        instance_id=instance_id,
        direction=Direction.IN,
        source="system",
        kind=Kind.INSTRUCTION,
        payload={"text": instruction},
    )
    return str(msg_id)
