archive_mode = on
archive_command = 'pgbackrest --stanza=agflow archive-push %p'
wal_level = replica
max_wal_senders = 3
archive_timeout = 60
include_if_exists = '/var/lib/postgresql/data/postgresql.conf'
